name: rx_state
description: State manager for flutter.
version: 0.0.1
homepage: https://github.com/freethinkel/rx_state.git

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
